# Generated by Django 3.0.2 on 2020-01-22 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomRequest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='num_text',
            new_name='room_num',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roomRequest.Room')),
            ],
        ),
    ]
